extends: ":workspace"
sandbox:
  network: restricted
  proxy:
    enabled: true
    enableSocks5: true
    enableSocks5Udp: false
    allowUpstreamProxy: false
    dangerouslyAllowAllUnixSockets: false
    allowLocalBinding: true
    mode: full
    domains:
      api.example.com: allow
